version: '3'

services:
  cpanel-sim:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./.env.local:/app/.env.local:ro
    restart: unless-stopped 