'use client';

import Script from 'next/script';

/**
 * Ezoic Integration Scripts
 *
 * Implements Ezoic's JavaScript integration for dual monetization alongside AdSense.
 * Uses third-party CMP (our custom Norwegian cookie banner) instead of Gatekeeper.
 *
 * Integration benefits:
 * - Works with AdSense via Mediation for split testing
 * - No DNS changes required
 * - Complete control over ad placements
 * - Lightweight client-side integration
 * - Custom Norwegian cookie consent (not Ezoic's default popup)
 *
 * Consent is managed via window._ezconsent set by cookieManager.ts
 *
 * @see https://docs.ezoic.com/docs/ezoicads/integration/
 */
export function EzoicScripts() {
  return (
    <>
      {/* Initialize _ezconsent BEFORE Ezoic scripts to prevent their popup */}
      <Script
        id="ezoic-consent-init"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window._ezconsent = window._ezconsent || {
              consent: false,
              analytics: false,
              advertising: false,
              functional: false
            };
          `,
        }}
      />

      {/* Ezoic Gatekeeper Consent Scripts - Required for rewarded ads pipeline */}
      <Script
        src="https://the.gatekeeperconsent.com/cmp.min.js"
        data-cfasync="false"
        strategy="beforeInteractive"
      />
      <Script
        async
        src="https://the.gatekeeperconsent.com/ccpa/v2/standalone.js"
        strategy="afterInteractive"
      />

      {/* Ezoic Header Script - Loads asynchronously */}
      <Script
        async
        src="//www.ezojs.com/ezoic/sa.min.js"
        strategy="afterInteractive"
      />

      {/* Ezoic Standalone Initialization + Rewarded Ads */}
      <Script
        id="ezoic-standalone-init"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.ezstandalone = window.ezstandalone || {};
            ezstandalone.cmd = ezstandalone.cmd || [];
            window.ezRewardedAds = window.ezRewardedAds || {};
            window.ezRewardedAds.cmd = window.ezRewardedAds.cmd || [];
            ezstandalone.cmd.push(function () {
              ezstandalone.initRewardedAds();
            });
          `,
        }}
      />

      {/* Ezoic Rewarded Ads Download Interceptor (generated by Ezoic AI Setup) */}
      <Script
        id="ezoic-rewarded-download-interceptor"
        strategy="lazyOnload"
        dangerouslySetInnerHTML={{
          __html: `
            (function() {
              var downloadLinkSelector = 'a[aria-label="Last ned Bilde"]';
              var pdfDownloadPending = false;

              function handlePDFDownload() {
                if (pdfDownloadPending) return;
                var downloadLink = document.querySelector(downloadLinkSelector);
                if (!downloadLink) return;
                var pdfUrl = downloadLink.getAttribute('href');
                if (!pdfUrl) return;

                if (!window.ezRewardedAds || !window.ezRewardedAds.ready) {
                  window.open(pdfUrl, '_blank', 'noopener,noreferrer');
                  return;
                }

                try {
                  window.ezRewardedAds.requestWithOverlay(
                    function(result) {
                      if (result.status && result.reward) {
                        pdfDownloadPending = true;
                        try {
                          window.open(pdfUrl, '_blank', 'noopener,noreferrer');
                        } catch (e) {
                          console.error('Ezoic Rewarded Ads: Error opening PDF:', e);
                        } finally {
                          setTimeout(function() { pdfDownloadPending = false; }, 1000);
                        }
                      }
                    },
                    {
                      header: "Se annonse for \\u00e5 laste ned!",
                      body: ["For \\u00e5 laste ned fargeleggingsarket m\\u00e5 du se en kort annonse.\\nDette hjelper oss \\u00e5 tilby gratis innhold."],
                      accept: "Se annonse",
                      cancel: "Avbryt"
                    },
                    {
                      rewardName: "PDF Download - Fargeleggingsark",
                      rewardOnNoFill: true,
                      alwaysCallback: true
                    }
                  );
                } catch (error) {
                  console.error('Ezoic Rewarded Ads: Error:', error);
                  window.open(pdfUrl, '_blank', 'noopener,noreferrer');
                }
              }

              function attachDownloadInterceptor() {
                var downloadLink = document.querySelector(downloadLinkSelector);
                if (!downloadLink) return;
                downloadLink.addEventListener('click', function(event) {
                  event.preventDefault();
                  event.stopPropagation();
                  event.stopImmediatePropagation();
                  handlePDFDownload();
                }, true);
              }

              if (document.readyState === 'interactive' || document.readyState === 'complete') {
                attachDownloadInterceptor();
              } else {
                document.addEventListener('DOMContentLoaded', attachDownloadInterceptor);
              }
            })();
          `,
        }}
      />
    </>
  );
}
